---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cosmonaut-cms"
spec:
  selector:
    matchLabels:
      app: "cosmonaut-cms"
  template:
    metadata:
      labels:
        app: "cosmonaut-cms"
    spec:
      serviceAccountName: cosmonaut-services
      containers:
        - name: "cosmonaut-admin"
          image: "gcr.io/cosmonaut-299500/cosmonaut/cms:$TAG"
          env:
            - name: MICRONAUT_APPLICATION_JSON
              value: '{"kubernetes":{ "client":{ "config-maps":{"enabled":true,"labels":[{"environment":"dev"}]}, "secrets":{"enabled":true,"labels":[{"environment":"dev"}]} }}}'
            - name: APLICACION_PUERTO
              value: "8080" 
          ports:
            - name: web
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "cosmonaut-cms"
spec:
  selector:
    app: "cosmonaut-cms"
  type: ClusterIP
  ports:
    - protocol: TCP
      name: web
      port: 8080